[webservers]
web-1 ansible_host=192.168.0.5
web-2 ansible_host=192.168.0.4

[loadbalancers]
load-balancer ansible_host=192.168.0.6

[all:vars]
ansible_user=devops
ansible_become=true
ansible_become_method=sudo
ansible_become_timeout=30
ansible_python_interpreter=/usr/bin/python3
